#!/bin/bash

. /etc/rc.d/init.d/functions

RETVAL=0
prog=oddmon
ODDMON=/usr/bin/monctl
lockfile=/var/lock/subsys/$prog
PID_FILE=/var/run/oddmon_aggregate.pid
CONF=/etc/oddmon/oddmon.cfg

start()
{
    [ -x $ODDMON ] || exit 5
    [ -f $CONF ] || exit 6
    
    $ODDMON aggregate --cfgfile $CONF --pid $PID_FILE && success || failure
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $lockfile
    echo 
    return $RETVAL
}

stop()
{
    # $ODDMON aggregate --cfgfile $CONF --stop
    echo -n "Stopping $prog"
    killproc -p $PID_FILE $ODDMON
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    echo
}

rh_status() {
    status -p $PID_FILE oddmon.py
}

rh_status_q() {
    rh_status > /dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        start
        ;;
    stop)
        if ! rh_status_q; then
            rm -f $lockfile
            exit 0
        fi
        stop
        ;;
    status)
#        rh_status
#        RETVAL=$?
#        if [ $RETVAL -eq 3 -a -f $lockfile ]; then
#            RETVAL=2
#        fi
        if ps aux | grep -q [m]onctl; then
            echo "Aggregator is running"
        else
            echo "Aggregator is not running"
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status}"
        RETVAL=2
esac
exit $RETVAL


