apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: oddmon
  name: oddmon
  namespace: stf008splunk
spec:
  # TODO: After we've gained some confidence with this config, we
  # can probably remove the 'paused' line
  paused: true
  replicas: 1
  selector:
    deploymentconfig: oddmon
  strategy:
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oddmon
        deploymentconfig: oddmon
    spec:
      containers:
        - image: docker-registry.default.svc:5000/stf008splunk/oddmon-is:latest
          imagePullPolicy: Always
          name: oddmon
          #ports:
          #  - containerPort: 8080
          #    protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/splunk
              name: volume-40qbn
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: volume-40qbn
          persistentVolumeClaim:
            claimName: splunkdata
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - oddmon
        from:
          kind: ImageStreamTag
          name: 'oddmon:latest'
          namespace: stf008splunk
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/stf008splunk/oddmon:latest
      type: ImageChange
    - type: ConfigChange

