apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: splunkdata
    annotations:
      # These two annotations are experimental, but will hopefully turn OFF
      # the NetApp snapshots.
      trident.netapp.io/snapshotDirectory: "false"
      trident.netapp.io/snapshotPolicy: "default"
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: splunk-forwarder-state
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
# Persistent volume for the RabbitMQ server
#- apiVersion: v1
#  kind: PersistentVolumeClaim
#  metadata:
#    name: rabbitmq-data
#  spec:
#    accessModes:
#    - ReadWriteOnce
#    resources:
#      requests:
#        storage: 50Gi        
kind: List
metadata: {}

